name: Node Backend Docker CI

on:
  push:
    branches:
      - master

jobs:
  build-docker-image:
    runs-on: ubuntu-latest

    steps:
      - name: ✅ Checkout Source Code
        uses: actions/checkout@v4

      - name: ✅ Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: ✅ Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: ✅ Build and Push Docker Image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: vinaydaripelly/student-backend:latest
